version: '3'

services:
  api:
    depends_on:
      - db
    links:
      - db
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: postech
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  data: