apiVersion: v1
kind: Secret
metadata:
  name: pos-tech-secret
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzX3Bhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9wb3MtdGVjaC1kYj9zY2hlbWE9cHVibGlj

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-tech-deployment
  labels:
    app: pos-tech-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pos-tech-deployment
    spec:
      containers:
        - name: pos-tech-image
          image: mmatiazzo/pos-tech-diner:4.0
          ports:
            - containerPort: 3333
          envFrom:
            - secretRef:
                name: pos-tech-secret
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
  selector:
    matchLabels:
      app: pos-tech-deployment

---
apiVersion: v1
kind: Service
metadata:
  name: pos-tech-service
spec:
  type: NodePort
  selector:
    app: pos-tech # Update this selector based on your PostgreSQL labels
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 3333
