apiVersion: v1
kind: Namespace
metadata:
  name: postech
---
apiVersion: v1
kind: Secret
metadata:
  name: pos-tech-secret
  namespace: postech
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzX3VzZXJuYW1lOnBvc3RncmVzX3Bhc3N3b3JkQHJkcy1wb3MtdGVjaC1kaW5lci5jcGl1cWNzMm92NTYudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvcG9zdGVjaGRpbmVyZGI=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-tech-deployment
  namespace: postech
  labels:
    app: pos-tech-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pos-tech-deployment
    spec:
      containers:
        - name: pos-tech-image
          image: 378188326309.dkr.ecr.us-east-1.amazonaws.com/pos-tech-diner-app:latest
          ports:
            - containerPort: 3333
          envFrom:
            - secretRef:
                name: pos-tech-secret
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
  selector:
    matchLabels:
      app: pos-tech-deployment

---
apiVersion: v1
kind: Service
metadata:
  name: pos-tech-service
  namespace: postech
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-name: test
spec:
  ports:
  - port: 80
    targetPort: 3333
    protocol: TCP
  type: LoadBalancer
  selector:
    app: pos-tech-deployment
