apiVersion: v1
kind: Secret
metadata:
  name: database-secret
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_DB: cG9zLXRlY2gtZGI=
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=

---

apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: proxy  # Update this selector based on your PostgreSQL labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5432
  type: NodePort  # Use ClusterIP for internal communication

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: database-pod
    spec:
      containers:
        - name: database-image
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: database-secret
  selector:
    matchLabels:
      app: database-pod