apiVersion: v1
kind: Secret
metadata:
  name: database-secret
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_DB: cG9zLXRlY2gtZGI=
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: database-secret
  selector:
    matchLabels:
      app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  type: ClusterIP # Use ClusterIP for internal communication
  ports:
    - port: 5432
